In [ ]:
import pandas as pd
from dotenv import load_dotenv
import os
load_dotenv()

URL = os.getenv("URL")

df = pd.read_csv("./Strokesdataset.csv")
df.groupby("stroke")["stroke"].agg(len)

stroke
0    42617
1      783
Name: stroke, dtype: int64

In [3]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,30669,Male,3.0,0,0,No,children,Rural,95.12,18.0,NaN,0
1,30468,Male,58.0,1,0,Yes,Private,Urban,87.96,39.2,never smoked,0
2,16523,Female,8.0,0,0,No,Private,Urban,110.89,17.6,NaN,0
3,56543,Female,70.0,0,0,Yes,Private,Rural,69.04,35.9,formerly smoked,0
4,46136,Male,14.0,0,0,No,Never_worked,Rural,161.28,19.1,NaN,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43400 entries, 0 to 43399
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 43400 non-null  int64
 1   gender             43400 non-null  object
 2   age                43400 non-null  float64
 3   hypertension       43400 non-null  int64
 4   heart_disease      43400 non-null  int64
 5   ever_married       43400 non-null  object
 6   work_type          43400 non-null  object
 7   Residence_type     43400 non-null  object
 8   avg_glucose_level  43400 non-null  float64
 9   bmi                41938 non-null  float64
 10  smoking_status     30108 non-null  object
 11  stroke             43400 non-null  int64
dtypes: float64(3), int64(4), object(5)
memory usage: 4.0+ MB

In [5]:
df.sort_values("age").head(20)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
8334,8029,Female,0.08,0,0,No,children,Urban,93.97,13.1,NaN,0
1389,47350,Female,0.08,0,0,No,children,Urban,139.67,14.1,NaN,0
9690,57792,Female,0.08,0,0,No,children,Urban,106.31,15.8,NaN,0
31171,12958,Male,0.08,0,0,No,children,Rural,122.01,14.6,NaN,0
3096,29955,Male,0.08,0,0,No,children,Rural,70.33,16.9,NaN,0
11805,43475,Female,0.08,0,0,No,children,Rural,135.52,12.8,NaN,0
9288,25195,Male,0.08,0,0,No,children,Urban,68.58,15.1,NaN,0
21995,68654,Female,0.08,0,0,No,children,Rural,111.09,12.2,NaN,0
39655,40667,Male,0.08,0,0,No,children,Urban,70.30,12.9,NaN,0
28657,26091,Male,0.08,0,0,No,children,Rural,84.93,30.6,NaN,0
15399,68046,Male,0.08,0,0,No,children,Rural,76.04,12.8,NaN,0
40472,30798,Female,0.08,0,0,No,children,Urban,108.82,16.7,NaN,0
14016,10739,Male,0.08,0,0,No,children,Urban,93.04,NaN,NaN,0
32971,36718,Female,0.08,0,0,No,children,Urban,67.55,NaN,NaN,0
40650,61897,Male,0.08,0,0,No,children,Urban,98.89,16.1,NaN,0
28973,34490,Male,0.08,0,0,No,children,Rural,97.03,12.1,NaN,0
43220,36634,Female,0.08,0,0,No,children,Rural,125.11,12.1,NaN,0
27455,27860,Male,0.16,0,0,No,children,Urban,92.54,15.3,NaN,0
3428,22877,Male,0.16,0,0,No,children,Urban,114.71,17.4,NaN,0
7535,53167,Female,0.16,0,0,No,children,Rural,60.67,13.8,NaN,0

In [6]:
ms = df[df["smoking_status"].isna()]
ms["work_type"].value_counts()

work_type
children         5525
Private          5249
Self-employed    1348
Govt_job         1094
Never_worked       76
Name: count, dtype: int64

In [7]:
ms[(ms["work_type"] != "children") & (ms["age"] < 18)].sort_values("age")

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
164,54975,Male,7.0,0,0,No,Self-employed,Rural,64.06,18.9,NaN,0
2,16523,Female,8.0,0,0,No,Private,Urban,110.89,17.6,NaN,0
3294,70833,Female,13.0,0,0,No,Private,Urban,62.57,20.9,NaN,0
39238,67664,Female,13.0,0,0,No,Never_worked,Urban,79.14,33.4,NaN,0
18719,62571,Female,13.0,0,0,No,Never_worked,Rural,61.33,22.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2063,1451,Female,17.0,0,0,No,Private,Urban,78.46,23.5,NaN,0
1913,56420,Male,17.0,1,0,No,Private,Rural,61.67,97.6,NaN,0
1753,65229,Female,17.0,0,0,No,Private,Rural,55.41,25.4,NaN,0
43230,12910,Female,17.0,0,0,No,Private,Rural,84.93,27.6,NaN,0
43231,29918,Female,17.0,0,0,No,Private,Rural,79.25,30.4,NaN,0

In [8]:
df.loc[
    (df["smoking_status"].isna()) &
    (df["work_type"] != "children") &
    (df["age"] < 18),
    "smoking_status"
] = "never smoked"

df.loc[
    df["work_type"] == "children",
    "smoking_status"
] = "never smoked"

In [9]:
df[(df["work_type"] != "children") & (ms["age"] < 18)].sort_values("age")

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
164,54975,Male,7.0,0,0,No,Self-employed,Rural,64.06,18.9,never smoked,0
2,16523,Female,8.0,0,0,No,Private,Urban,110.89,17.6,never smoked,0
3294,70833,Female,13.0,0,0,No,Private,Urban,62.57,20.9,never smoked,0
39238,67664,Female,13.0,0,0,No,Never_worked,Urban,79.14,33.4,never smoked,0
18719,62571,Female,13.0,0,0,No,Never_worked,Rural,61.33,22.1,never smoked,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2063,1451,Female,17.0,0,0,No,Private,Urban,78.46,23.5,never smoked,0
1913,56420,Male,17.0,1,0,No,Private,Rural,61.67,97.6,never smoked,0
1753,65229,Female,17.0,0,0,No,Private,Rural,55.41,25.4,never smoked,0
43230,12910,Female,17.0,0,0,No,Private,Rural,84.93,27.6,never smoked,0
43231,29918,Female,17.0,0,0,No,Private,Rural,79.25,30.4,never smoked,0

In [10]:
ms = df[df["smoking_status"].isna()]
ms["work_type"].value_counts()

work_type
Private          4780
Self-employed    1300
Govt_job         1073
Never_worked       21
Name: count, dtype: int64

In [11]:
pv = ms[(ms["work_type"] == "Never_worked") & (ms["age"] < 18)]
pv.head(21)

Empty DataFrame
Columns: [id, gender, age, hypertension, heart_disease, ever_married, work_type, Residence_type, avg_glucose_level, bmi, smoking_status, stroke]
Index: []

In [12]:
df.dropna(inplace=True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35104 entries, 0 to 43399
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 35104 non-null  int64
 1   gender             35104 non-null  object
 2   age                35104 non-null  float64
 3   hypertension       35104 non-null  int64
 4   heart_disease      35104 non-null  int64
 5   ever_married       35104 non-null  object
 6   work_type          35104 non-null  object
 7   Residence_type     35104 non-null  object
 8   avg_glucose_level  35104 non-null  float64
 9   bmi                35104 non-null  float64
 10  smoking_status     35104 non-null  object
 11  stroke             35104 non-null  int64
dtypes: float64(3), int64(4), object(5)
memory usage: 3.5+ MB

In [ ]:
import psycopg2
from sqlalchemy import create_engine

engine = create_engine(URL)

df.to_sql("stroke_data", engine, if_exists="replace", index=False)

In [15]:
df.groupby("stroke")["stroke"].agg(len)

stroke
0    34555
1      549
Name: stroke, dtype: int64

In [16]:
ohe = pd.get_dummies(df)
ohe.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35104 entries, 0 to 43399
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              35104 non-null  int64
 1   age                             35104 non-null  float64
 2   hypertension                    35104 non-null  int64
 3   heart_disease                   35104 non-null  int64
 4   avg_glucose_level               35104 non-null  float64
 5   bmi                             35104 non-null  float64
 6   stroke                          35104 non-null  int64
 7   gender_Female                   35104 non-null  bool
 8   gender_Male                     35104 non-null  bool
 9   gender_Other                    35104 non-null  bool
 10  ever_married_No                 35104 non-null  bool
 11  ever_married_Yes                35104 non-null  bool
 12  work_type_Govt_job              35104 non-null  bool
 13  work_type_Never_worked          35104 non-null  bool
 14  work_type_Private               35104 non-null  bool
 15  work_type_Self-employed         35104 non-null  bool
 16  work_type_children              35104 non-null  bool
 17  Residence_type_Rural            35104 non-null  bool
 18  Residence_type_Urban            35104 non-null  bool
 19  smoking_status_formerly smoked  35104 non-null  bool
 20  smoking_status_never smoked     35104 non-null  bool
 21  smoking_status_smokes           35104 non-null  bool
dtypes: bool(15), float64(3), int64(4)
memory usage: 2.6 MB

In [17]:
ohe.to_sql("stroke_data_ohe", engine, if_exists="replace", index=False)

104